### ISSUE TITLE
Unstable work on unbuffered ACSI port (e.g. STf).

### ISSUE THREAD

**Issue by TzOk83** [retro16/acsi2stm#7]
I can't get it to work on Atari STfm, on STe it works flawlessly and very fast (~1MB/s). I think it can be caused, by the fact, that STf doesn't have any buffers between DMA chip and ACSI port, while STe - has. If I load the driver from the disk, I can browse the card on the STf, but writing to it, corrupts it completely. I'm using P. Putnik's driver.

P.S.
For some reason, if I upload the program to the BluePill from Arduino IDE via the STLink, it doesn't work (but reacts on ACSI activity), while when I upload it via the Serial it works. It also works if I export the binary file from Arduino IDE and upload it to the BluePill via the STLink, with the STM32 Cube.

**Comment by retro16** [comment]
Thansk for the detailled feedback.

I usually work on a STE, but testing on a 520STF shows indeed signs of data corruption. Strangely, it's not 100% corrupt, its mostly right: I could copy a PRG, reset, and run it successfully, but the file system quickly degrades (I'm using ICD). In my case that probably could be worked around using a driver that does verify and retries.

The electrical compatibility issue is a serious lead, I wasn't aware of these hardware differences. Having an oscilloscope of D0 and ACK during a write operation would help. I'm working on soomething else right now but I'll try doing it in a near future.

I have STLink issues too. STLink issues may be because of direct port access for GPIO or systick disabling (not sure). I do push the STM to its limits with that version. I don't really care, I use serial anyway.

**Comment by retro16** [comment]
Just an idea that came across my mind: maybe the DMA data lines are slow on the STfm, so I did a testing branch "dmadelay" that delays sampling. I doubt it changes anything, but if you could test it, that would be appreciated.

By the way, there are known issues on some STf with writing, and it seems that these aren't able to write anything tio their DMA/ACSI port. Do you have any way to check that there are actually some signals on D0-D7 during a write operation ? (oscilloscope, logic analyzer ...)

**Comment by TzOk83** [comment]
I can check signals on the bus, but UltraSatan works fine, on that machine.

**Comment by retro16** [comment]
Ok if UltraSatan works, no need to check the signals, the issue is on the STM side. I was able to reproduce anyway, and it seems my "dmadelay" branch improves things a bit. I might make a DMA test application some day ...

**Comment by TzOk83** [comment]
I have tried today and still no luck  with the autoboot, yet writes now work correctly.

I have tried on the same SD card and same ACSI cable as my UltraSatan.

I can copy many MBs of data and everything works stable. The dmadelay version is actually slightly... faster than the current release version (1010 vs 990 kB/s).

**Comment by mamejay** [comment]
I have built a unit up and programmed using a STLink and get the same issue as TzOk83.  I get activity LED on the STM but will not detect the card.  My serial adapters have decided they do not want to work.  I have another on order.  Hope this works as I have checked all connection and everything is connected correctly.

**Comment by VonHirsch** [comment]
Hello, i'm getting ready to build a unit and came across this thread.  I'd like to use it on a 520STF.  Is it possible that this issue is related to the ["DMA" issue](https://www.exxoshost.co.uk/atari/last/DMAfix/)?

**Comment by retro16** [comment]
Things have changed a lot since v2.1. I'm now pretty confident that commands aren't skipped anymore, but reality proves that there are still issues for some people that I can't reproduce.
If issues still arise, traces of the following signals during a failed write operation would be greatly appreciated (a few periods should be enough):

* DRQ (ACSI pin 19)
* ACK (ACSI pin 14)
* D0 (ACSI pin 1)

And another trace with the following pins captured during a write command (one A1 pulse and a few CS/IRQ pulses is enough):

* IRQ (ACSI pin 10)
* CS (ACSI pin 9)
* A1 (ACSI pin 16)

Pins are listed in order of importance, if your oscilloscope/logic analyzer doesn't have enough inputs, just take the top of the list.

**Comment by luciust** [comment]
Well I got Two STF and and 4 STEs.
The <2.1 version was corrupting data but working on STE with older DMA. The 2.1 doesn't - Putnik or ICD - they can't even read the filesystem. STE has pullups on DMA bus.

I need to check on STFs and one STE with newer (001) DMA I got. One of them (strangely not the one with 001 DMA) works fine with CosmosEX and the STF works with aftermarket SCSI - ACSI HDD from the era.

So - need to test and get back here! Got a scope and logic analyzer at disposal

**Comment by luciust** [comment]
OK, So far:
- STE, old DMA, pullups, TOS 2.06 - no go
- STE, new DMA, no pullups, TOS 1.62 - no go
- STF, old DMA, pullups, TOS 1.04 - no go

The effect is the same - Putnik's partiition program takes  2 mins to find the "HDD" and either shows 0MB or 128MB.

Double checking the connections and the plan is to attach console and turn on debug.

**Comment by TzOk83** [comment]
I may confirm the same - v2.1 doesn't work for me at all. On my STE v2.0, and v2.0 "dmadelay" were working, including autoboot feature (but only on STE).

Are you aware of the fact, that the Data Request (19) signal timing given in the official documentation is apparently wrong?

**Comment by retro16** [comment]
Version 2.2 leaves data on the bus after the ACK rises for a small amount of time. The ACSI doc specifies a minimum of 20ns so I removed code inlining and added a single NOP to make sure that this requirement is exceeded. This is very similar to what "dmadelay" did but in a cleaner way.

ACSI_FAST_DMA define restores the faster inline code of version 2.1 if set to 1.

Now, trying different combinations of ACSI_ACK_FILTER, ACSI_CS_FILTER and ACSI_FAST_DMA should allow adjusting to any reasonable delay required by different versions of the DMA chip. As a general rule of thumb, slower should mean more compatible.

**Comment by z80micro-mc** [comment]
I am in the process of building an ACSI2STM for my STs 520STM & 520STFM and have observed that most of the designs would appear to use an Arduino micro SD adapter.  As far as I can ascertain the vast majority of these are designed for 5V TTL operation and include both 5->3v3 regulators and 3v <-> 5V buffers.  The ACSI design would appear to use the TTL compatible interfaces on the ACSI side However, the micro SD side pins are not TTL compatible.  Ihave not not seen articles on removing the 5v-> 3v3 regulator and feeding in 3v3  from the STM nor of removing the LVC125 level converters and ffeding directly into th eSTM from the SD card. Could this be adding to the corruption?

Peter

**Comment by retro16** [comment]
@z80micro-mc you probably found a very important issue. My prototype uses microSD->SD converters as SD slots, so no electronics (except a 100nF SMD decoupling capacitor, very important). I previously had issues, but simply because the converter was faulty (these things tend to wear). Soldering a new converter, I have no issue at all.
I can push any card (from old no-name 2GB to brand new SanDisk) to 36MHz on a hand-soldered prototype with 3cm wires and header pins. With the newer, much more stable, version 2.3c I just released, compatibility issues will probably be a thing of the past.

**Comment by TzOk83** [comment]
2.31 still doesn't want to autoboot on my STfm (TOS 1.04), while it works fine with my STe (TOS 2.06 and 1.62).

**Comment by retro16** [comment]
Thanks @TzOk83  for the quick feedback, it really helps.

Can you try with the following settings in acsi2stm.h ?

#define ACSI_ACK_FILTER 2
#define ACSI_CS_FILTER 2
#define ACSI_FAST_DMA 0

ACSI_FAST_DMA 0 brings back the workaround of the old dmadelay branch. Combined with ACK_FILTER to the maximum, this will add a lot of delay to the DMA transfer, which should help mitigating the lack of buffers and the fact that the STM32 outputs 3.3V instead of 5V. I am probably missing an important detail, but without a problematic machine at hand, it's difficult to pinpoint the issue.

If nothing works, it probably would require driving the bus with pull-ups and tristate to reach 5V on data signals, which changes the logic a lot and will make transfers super slow. Not sure if it's worth it.

**Comment by TzOk83** [comment]
I think this may be important - the "dummy bootsector" message shows on the STfm, despite it has an autoboot enabled SD card. If I load ICD driver from the floppy disk it works.

**Comment by retro16** [comment]
Super cool, thanks a lot for your help and your patience for helping solving this issue. It's strange that you had the dummy bootsector message working but not ICD. Maybe it's because of the size of the binary.

Anyway, I will set ACSI_ACK_FILTER to 2 by default from now on, the aim is to have a conservative "official" image that trades more compatibility for less speed, and the performance loss of ACK_FILTER to 2 is really minimal. It introduces a lag of about 40ns per byte, which matches more or less what is described in the page you linked a while ago.

Feel free to mark the issue as closed if it is stable for you.

**Comment by luciust** [comment]
Wow, so I can get back to soldering! Great news, thanks!
